question_data= [
    {"category": "Science: Computers", "questions_list": [
        {"question": "The Windows ME operating system was released in the year 2000.", "correct_answer": "True"},
        {"question": "Time on Computers is measured via the EPOX System.", "correct_answer": "False"},
        {"question": "The Python programming language gets its name from the British comedy group Monty Python", "correct_answer": "True"},
        {"question": "In most programming languages, the operator ++ is equivalent to the statement +=1.","correct_answer": "True"},
        {"question": "The Windows 7 operating system has six main editions.", "correct_answer": "True"},
        {"question": "The logo for Snapchat is a Bell.", "correct_answer": "False"},
        {"question": "Ada Lovelace is often considered the first computer programmer.", "correct_answer": "True"},
        {"question": "HTML stands for Hypertext Markup Language.", "correct_answer": "True"},
        {"question": "Pointers were not used in the original C programming language; they were added later on in C++.","correct_answer": "False"},
        {"question": "RAM stands for Random Access Memory.", "correct_answer": "True"}]},
    {"category": "Science: Nature", "questions_list": [
        {"question": "A plant that has a life cycle for more than a year is known as an annual.","correct_answer": "False"},
        {"question": "An average human can go two weeks without water.", "correct_answer": "False"},
        {"question": "Psychology is the science of behavior and mind.", "correct_answer": "True"},
        {"question": "Water always boils at 100 deg C, 212 degF, 373.15K, no matter where you are.","correct_answer": "False"},
        {"question": "An exothermic reaction is a chemical reaction that releases energy by radiating electricity.","correct_answer": "False"},
        {'question': "Salt is 100% composed of Sodium.", "correct_answer": "False"},
        {"question": "Igneous rocks are formed by excessive heat and pressure.", "correct_answer": "False"},
        {"question": "Not including false teeth; A human has two sets of teeth in their lifetime.","correct_answer": "True"},
        {"question": "An atom contains a nucleus.", "correct_answer": "True"},
        {"question": "An Astronomical Unit is the distance between Earth and the Moon.","correct_answer": "False"}]},
    {"category": "Entertainment: Music", "questions_list": [
        {"question": "The music group Daft Punk got their name from a negative review they recieved.","correct_answer": "True"},
        {"question": "In 1993, Prince changed his name to an unpronounceable symbol because he was unhappy with his contract with Warner Bros.","correct_answer": "True"},
        {"question": "Stevie Wonder's real name is Stevland Hardaway Morris.", "correct_answer": "True"},
        {"question": "The song 'Stronger Than You' is a single by Estelle, who played Garnet in Steven Universe.","correct_answer": "True"},
        {"question": "Eurobeat is primarily an Italian genre of music.", "correct_answer": "True",},
        {"question": "A Saxophone is a brass instrument.", "correct_answer": "False"},
        {"question": "The alternative rock band, They Might Be Giants, released their album 'Flood' in 1990. ","correct_answer": "True"},
        {"question": "John Williams composed the music for 'Star Wars'.", "correct_answer": "True"},
        {"question": "The music video to The Buggle's 'Video Killed the Radio Star' was the first music video to broadcast on MTV.","correct_answer": "True"},
        {"question": "Lead Singer Rivers Cuomo of American rock band Weezer attended Harvard.","correct_answer": "True"}]},
    {"category": "Entertainment: Film", "questions_list": [
        {"question": "Brandon Routh plays the titular character in the movie 'John Wick'.","correct_answer": "False"},
        {"question": "The word 'Inception' came from the 2010 blockbuster hit 'Inception'.","correct_answer": "False"},
        {"question": "George Lucas directed the entire original Star Wars trilogy.", "correct_answer": "False"},
        {"question": "Ewan McGregor did not know the name of the second prequel film of Star Wars during and after filming.","correct_answer": "True"},
        {"question": "The 2010 film 'The Social Network' is a biographical drama film about MySpace founder Tom Anderson.","correct_answer": "False"},
        {"question": "Han Solo's co-pilot and best friend, 'Chewbacca', is an Ewok.","correct_answer": "False"},
        {"question": "Matt Damon played an astronaut stranded on an extraterrestrial planet in both of the movies Interstellar and The Martian.","correct_answer": "True"},
        {"question": "In the original Star Wars trilogy, Alec Guinness provided the voice for Darth Vader.","correct_answer": "False"},
        {"question": "Shaquille Neal appeared in the 1997 film 'Space Jam'.","correct_answer": "False"},
        {"question": "'Foodfight' earned less than $80,000 at box office.", "correct_answer": "True",}]},
    {"category": "Geography", "questions_list": [
        {"question": "A group of islands is called an 'archipelago'.", "correct_answer": "True"},
        {"question": "Toronto is the capital city of the North American country of Canada.","correct_answer": "False"},
        {"question": "California is larger than Japan.", "correct_answer": "True"},
        {"question": "St. Louis is the capital of the US State Missouri.", "correct_answer": "False"},
        {"question": "Nova Scotia is on the east coast of Canada.","correct_answer": "True"},
        {"question": "Ottawa is the capital of Canada.", "correct_answer": "True", "incorrect_answers": ["False"]},
        {"question": "The Republic of Malta is the smallest microstate worldwide.", "correct_answer": "False"},
        {"question": "Hungary is the only country in the world beginning with H.","correct_answer": "False"},
        {"question": "There is an island in Japan called kunoshima, A.K.A. 'Rabbit Island', so named because of it's huge population of rabbits.","correct_answer": "True"}]},

    {"category": "History", "questions_list": [
        {"question": "Adolf Hitler was a german soldier in World War I.", "correct_answer": "True"},
        {"question": "Thomas Crapper was a plumber who invented the flushing toilet.","correct_answer": "False"},
        {"question": "United States President John F. Kennedy was assassinated during his presidential motorcade in Atlanta, Georgia on November 22nd, 1963.","correct_answer": "False"},
        {"question": "The United States of America declared their independence from the British Empire on July 4th, 1776.","correct_answer": "True"},
        {"question": "The United States Department of Homeland Security was formed in response to the September 11th attacks.","correct_answer": "True"},
        {"question": "The United States was a member of the League of Nations.", "correct_answer": "False"},
        {"question": "Former United States Presidents John Adams and Thomas Jefferson died within hours of each other.","correct_answer": "True"},
        {"question": "The Cold War ended with Joseph Stalin&#039;s death.", "correct_answer": "False",},
        {"question": "The Spitfire originated from a racing plane.","correct_answer": "True"},
        {"question": "In World War ll, Great Britian used inflatable tanks on the ports of Great Britain to divert Hitler away from Normandy\/D-day landing.","correct_answer": "True"}]},

    {"category": "Animals", "questions_list": [
        {"question": "In 2016, the IUCN reclassified the status of Giant Pandas from endangered to vulnerable.","correct_answer": "True"},
        {"question": "The freshwater amphibian, the Axolotl, can regrow it's limbs.", "correct_answer": "True"},
        {"question": "Rabbits can see what's behind themselves without turning their heads.","correct_answer": "True"},
        {"question": "The internet browser Firefox is named after the Red Panda.", "correct_answer": "True"},
        {"question": "A bear does NOT defecate during hibernation. ","correct_answer": "True"},
        {"question": "The Axolotl is an amphibian that can spend its whole life in a larval state.","correct_answer": "True"},
        {"question": "A flock of crows is known as a homicide.", "correct_answer": "False"},
        {"question": "A caterpillar has more muscles than humans do.", "correct_answer": "True"},
        {"question": "The Killer Whale is considered a type of dolphin.","correct_answer": "True"}]},

    {"category": "General Knowledge", "questions_list": [
        {"question": "The color orange is named after the fruit.", "correct_answer": "True"},
        {"question": "Ping-Pong originated in England", "correct_answer": "True"},
        {"question": "You can legally drink alcohol while driving in Mississippi.", "correct_answer": "True"},
        {"question": "Scotland voted to become an independent country during the referendum from September 2014.","correct_answer": "False"},
        {"question": "The Lego Group was founded in 1932.", "correct_answer": "True"},
        {"question": "Bulls are attracted to the color red.","correct_answer": "False"},
        {"question": "Vietnam's national flag is a red star in front of a yellow background.","correct_answer": "False"},
        {"question": "One of Donald Trump&#039;s 2016 Presidential Campaign promises was to build a border wall between the United States and Mexico.","correct_answer": "True"},
        {"question": "The Great Wall of China is visible from the moon.", "correct_answer": "False"},
        {"question": "A pasodoble is a type of Italian pasta sauce.","correct_answer": "False"}]}
];
